# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
gradle_execution_rights: &gradle_execution_rights
  run:
    name: Setup gradlew execution rights
    command: chmod +x gradlew

version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-28
    working_directory: ~/Android-MVVM
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      # Download and cache dependencies
      - *gradle_execution_rights
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          pre:
            - echo y | android update sdk --no-ui --all --filter "platform-tools, tools"
            - echo y | android update sdk --no-ui --all --filter "android-25, build-tools-25.0.2"
            - echo y | android update sdk --no-ui --all --filter "extra-android-m2repository"
            - echo y | android update sdk --no-ui --all --filter "extra-android-support"
          command: chmod +x ./gradlew
          command: chmod +x gradlew
          command: ./gradlew --gradle-version 4.8 --distribution-type all
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradlew
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      # run tests!
      - run:
          name: Run Tests
          command: ./gradlew test
      - store_artifacts:
          path: app/build/reports
          destination: reports